apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/pod-name: prometheus-user-workload-0
  name: prometheus-user-workload-0
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    prometheus: user-workload
    statefulset.kubernetes.io/pod-name: prometheus-user-workload-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/pod-name: prometheus-user-workload-1
  name: prometheus-user-workload-1
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    prometheus: user-workload
    statefulset.kubernetes.io/pod-name: prometheus-user-workload-1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    kubernetes.io/pod-name: prometheus-user-workload-0
  name: prometheus-user-workload-0
  namespace: openshift-user-workload-monitoring
spec:
  tls:
    termination: passthrough
  to:
    kind: Service
    name: prometheus-user-workload-0
    weight: 100
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    kubernetes.io/pod-name: prometheus-user-workload-1
  name: prometheus-user-workload-1
  namespace: openshift-user-workload-monitoring
spec:
  tls:
    termination: passthrough
  to:
    kind: Service
    name: prometheus-user-workload-1
    weight: 100
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conprof
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: conprof
  namespace: openshift-user-workload-monitoring

