---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eagle
  name: eagle-{{.Iteration}}-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eagle-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eagle-{{.Iteration}}-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - image: quay.io/rsevilla/eagle:latest
        imagePullPolicy: Always
        name: eagle
        command: ["eagle"]
        args:
          - -tempo={{.tempo}}
          - -label-value-explosion={{.labelValueExplosion}}
          - -label-name-explosion={{.labelNameExplosion}}
          - -explode-samples-scraped={{.increaseSamples}}
        ports:
          - containerPort: 8080
            name: metrics
      restartPolicy: Always

