---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eagle-{{.Iteration}}-{{.Replica}}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: eagle-{{.Iteration}}-{{.Replica}}
