{
 "title": "Prometheus performance",
 "description": "Prometheus performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "_infra_node",
    "label": "Infra",
    "query": "label_values(kube_node_role{role=\"infra\"}, node)"
   },
   {
    "name": "block_device",
    "label": "Block device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Replica Memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"prometheus-.+\",container=\"prometheus\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_rss{container=\"prometheus-operator\"}",
     "legendFormat": "{{namespace}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{pod=~\"prometheus.+\",container=~\"prometheus|prometheus-operator\"}[2m])*100",
     "legendFormat": "{{ namespace }}: {{ pod }}"
    }
   ]
  },
  {
   "title": "Appended samples rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job,namespace) (rate(prometheus_tsdb_head_samples_appended_total{namespace=~\"openshift-monitoring|openshift-user-workload-monitoring\"}[2m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Head time series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cluster monitoring operator reconcile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cluster_monitoring_operator_reconcile_attempts_total[5m])",
     "legendFormat": "Reconcile rate"
    },
    {
     "expr": "rate(cluster_monitoring_operator_reconcile_errors_total[5m])",
     "legendFormat": "Reconcile errors"
    }
   ]
  },
  {
   "title": "Prometheus operator memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{container=\"prometheus-operator\"}",
     "legendFormat": "{{ namespace }}: {{ container }}"
    }
   ]
  },
  {
   "title": "Prometheus operator CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{container=\"prometheus-operator\"}[2m]) * 100",
     "legendFormat": "{{ namespace }}: {{ container }}"
    }
   ]
  },
  {
   "title": "Cluster version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster_version{type=\"current\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 35
   }
  },
  {
   "title": "Current Node Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(kube_node_info{})", "legendFormat": "Number of nodes" },
    {
     "expr": "sum(kube_node_status_condition{status=\"true\"}) by (condition) > 0",
     "legendFormat": "Node: {{ condition }}"
    }
   ]
  },
  {
   "title": "Current Namespace Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{})",
     "legendFormat": "Namespace Count"
    }
   ]
  },
  {
   "title": "Current Pod Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{}) by (phase) > 0",
     "legendFormat": "{{ phase}} Pods"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(kube_node_info{})", "legendFormat": "Number of nodes" }
   ]
  },
  {
   "title": "Namespace count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(kube_namespace_created{})",
     "legendFormat": "Namespace count"
    }
   ]
  },
  {
   "title": "Pod count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{phase}} pods"
    }
   ]
  },
  {
   "title": "Secret count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "count(kube_secret_info{})", "legendFormat": "secrets" }
   ]
  },
  {
   "title": "Deployment count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(kube_deployment_labels{})",
     "legendFormat": "Deployments"
    }
   ]
  },
  {
   "title": "Configmap count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "count(kube_configmap_info{})", "legendFormat": "Configmaps" }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(ALERTS{severity!=\"none\"}) by (alertname, severity))",
     "legendFormat": "{{severity}}: {{alertname}}"
    }
   ]
  },
  {
   "title": "Top 10 container RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, container_memory_rss{namespace!=\"\",name!=\"\"})",
     "legendFormat": "{{ namespace }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Top 10 container CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(container_cpu_usage_seconds_total{namespace!=\"\",name!=\"\"}[2m])*100)",
     "legendFormat": "{{ namespace }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Goroutines count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(go_goroutines{}) by (job,instance))",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Infra: $_infra_node",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 8, "w": 0, "x": 0, "y": 1 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 79
   },
   "repeat": "_infra_node"
  },
  {
   "title": "CPU Basic: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode)(rate(node_cpu_seconds_total{instance=~\"$_infra_node\",job=~\".*\"}[5m])) * 100",
     "legendFormat": "Busy {{mode}}"
    }
   ]
  },
  {
   "title": "System Memory: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=~\"$_infra_node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$_infra_node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$_infra_node\"} + node_memory_Buffers_bytes{instance=~\"$_infra_node\"}",
     "legendFormat": "Cached + Buffers"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$_infra_node\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk throughput: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[2m])",
     "legendFormat": "{{ device }} - read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[2m])",
     "legendFormat": "{{ device }} - write"
    }
   ]
  },
  {
   "title": "Disk IOPS: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[2m])",
     "legendFormat": "{{ device }} - read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[2m])",
     "legendFormat": "{{ device }} - write"
    }
   ]
  },
  {
   "title": "Network Utilization: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[5m]) * 8",
     "legendFormat": "{{instance}} - {{device}} - RX"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[5m]) * 8",
     "legendFormat": "{{instance}} - {{device}} - TX"
    }
   ]
  },
  {
   "title": "Network Packets: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[5m])",
     "legendFormat": "{{instance}} - {{device}} - RX"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[5m])",
     "legendFormat": "{{instance}} - {{device}} - TX"
    }
   ]
  },
  {
   "title": "Network packets drop: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(node_network_receive_drop_total{instance=~\"$_infra_node\"}[2m]))",
     "legendFormat": "rx-drop-{{ device }}"
    },
    {
     "expr": "topk(10,rate(node_network_transmit_drop_total{instance=~\"$_infra_node\"}[2m]))",
     "legendFormat": "tx-drop-{{ device }}"
    }
   ]
  },
  {
   "title": "Conntrack stats: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$_infra_node\"}",
     "legendFormat": "conntrack_entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$_infra_node\"}",
     "legendFormat": "conntrack_limit"
    }
   ]
  },
  {
   "title": "Top 10 container CPU: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",name!=\"\",node=~\"$_infra_node\",namespace!=\"\",namespace=~\"$namespace\"}[5m])) by (namespace,name,service) * 100)",
     "legendFormat": "{{ namespace }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Top 10 container RSS: $_infra_node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, container_memory_rss{container!=\"POD\", name!=\"\",node=~\"$_infra_node\",namespace!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "{{ namespace }} - {{ name }}"
    }
   ]
  }
 ]
}